import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { api, config, saveConfig } from './api';
import './styles.css';

const active = new Set(['queued', 'leased', 'running']);
const stamp = (value) => value ? new Date(value).toLocaleString() : '—';
const Status = ({ value }) => <span className={`status ${value}`}>{value}</span>;

function Settings({ onConnected }) {
  const [baseUrl, setBaseUrl] = useState(config.baseUrl); const [token, setToken] = useState(config.token); const [error, setError] = useState('');
  async function connect(event) { event.preventDefault(); saveConfig({ baseUrl: baseUrl.replace(/\/$/, ''), token }); try { const me = await api('/v1/me'); setError(''); onConnected(me); } catch (e) { setError(e.message); } }
  return <main className="login"><section className="card"><p className="eyebrow">TRANSPORT LOOKOUT</p><h1>Operator Console</h1><p>Connect to an authorized Transport Lookout control plane.</p><form onSubmit={connect}><label>API URL<input value={baseUrl} onChange={e => setBaseUrl(e.target.value)} /></label><label>Access token<input type="password" value={token} onChange={e => setToken(e.target.value)} /></label><button>Connect</button>{error && <p className="error">{error}</p>}</form></section></main>;
}

function App() {
  const [me, setMe] = useState(null); const [tab, setTab] = useState('dashboard'); const [data, setData] = useState({ scopes: [], profiles: [], runs: [], schedules: [], audit: [], exposureSummary: null }); const [error, setError] = useState('');
  async function refresh() { try { const [scopes, profiles, runs, schedules, audit, exposureSummary] = await Promise.all([api('/v1/inventory/scopes'), api('/v1/scan-profiles'), api('/v1/scan-runs'), api('/v1/schedules'), api('/v1/audit-events').catch(() => []), api('/v1/exposures/summary')]); setData({ scopes, profiles, runs, schedules, audit, exposureSummary }); setError(''); } catch (e) { setError(e.message); } }
  useEffect(() => { if (!me) return; refresh(); const timer = setInterval(refresh, 5000); return () => clearInterval(timer); }, [me]);
  if (!me) return <Settings onConnected={setMe} />;
  const props = { ...data, refresh, setError };
  return <div className="shell"><aside><p className="eyebrow">TRANSPORT LOOKOUT</p><h2>Operations</h2>{['dashboard','exposures','inventory','profiles','runs','schedules','audit'].map(item => <button key={item} className={tab === item ? 'nav active' : 'nav'} onClick={() => setTab(item)}>{item}</button>)}<div className="identity">{me.subject}<br/><Status value={me.role} /></div></aside><main className="content">{error && <p className="error">{error}</p>}<header><h1>{tab}</h1><button className="secondary" onClick={refresh}>Refresh</button></header>{tab === 'dashboard' && <Dashboard {...props} />}{tab === 'exposures' && <Exposures {...props} />}{tab === 'inventory' && <Inventory {...props} />}{tab === 'profiles' && <Profiles {...props} />}{tab === 'runs' && <Runs {...props} />}{tab === 'schedules' && <Schedules {...props} />}{tab === 'audit' && <Audit {...props} />}</main></div>;
}

function Dashboard({ runs, scopes, profiles }) { const counts = runs.reduce((a, run) => ({ ...a, [run.status]: (a[run.status] || 0) + 1 }), {}); return <><div className="metrics"><Metric label="Approved scopes" value={scopes.filter(s => s.approved).length} /><Metric label="Profiles" value={profiles.length} /><Metric label="Active runs" value={runs.filter(r => active.has(r.status)).length} /><Metric label="Dead-letter shards" value={runs.flatMap(r => r.shards).filter(s => s.status === 'dead_letter').length} /></div><h2>Recent runs</h2><RunTable runs={runs.slice(0, 8)} /></>; }
function Metric({ label, value }) { return <article className="metric"><span>{label}</span><strong>{value}</strong></article>; }
function Exposures({ scopes, exposureSummary }) { const [items, setItems] = useState([]); const [scope, setScope] = useState(''); const [host, setHost] = useState(''); const [port, setPort] = useState(''); const [service, setService] = useState(''); const [offset, setOffset] = useState(0); const pageSize = 100; useEffect(() => { const params = new URLSearchParams({ limit: pageSize, offset }); if (scope) params.set('scope_id', scope); if (host) params.set('host', host); if (port) params.set('port', port); if (service) params.set('service', service); api(`/v1/exposures?${params}`).then(setItems).catch(() => setItems([])); }, [scope, host, port, service, offset]); function filter(e) { e.preventDefault(); setOffset(0); setScope(e.currentTarget.scope.value); setHost(e.currentTarget.host.value); setPort(e.currentTarget.port.value); setService(e.currentTarget.service.value); } return <><div className="metrics"><Metric label="Open hosts" value={exposureSummary?.open_hosts ?? 0}/><Metric label="Open services" value={exposureSummary?.open_services ?? 0}/><Metric label="Unique ports" value={exposureSummary?.unique_ports ?? 0}/><Metric label="Last observation" value={exposureSummary?.latest_observation_at ? new Date(exposureSummary.latest_observation_at).toLocaleDateString() : '—'}/></div><Form title="Filter current exposures" onSubmit={filter}><select name="scope" defaultValue={scope}><option value="">All scopes</option>{scopes.map(s=><option key={s.id} value={s.id}>{s.name} · {s.cidr}</option>)}</select><input name="host" defaultValue={host} placeholder="Host, e.g. 192.168.1.1"/><input name="port" type="number" min="1" max="65535" defaultValue={port} placeholder="Port, e.g. 443"/><input name="service" defaultValue={service} placeholder="Service, e.g. https"/><button>Apply filters</button></Form><Table headers={['Host','Port','Service','Product/version','Scope','First seen','Last seen']} rows={items.map(item=>[item.address,`${item.port}/${item.protocol}`,item.service || 'unknown',[item.product,item.version].filter(Boolean).join(' ') || '—',scopes.find(s=>s.id===item.inventory_scope_id)?.name || item.zone,stamp(item.first_seen_at),stamp(item.last_seen_at)])}/><div className="pager"><button className="secondary" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-pageSize))}>Previous</button><span>Showing {offset+1}–{offset+items.length}</span><button className="secondary" disabled={items.length<pageSize} onClick={()=>setOffset(offset+pageSize)}>Next</button></div></>; }
function Inventory({ scopes, refresh, setError }) { const [name, setName] = useState(''); const [cidr, setCidr] = useState(''); async function add(e) { e.preventDefault(); try { await api('/v1/inventory/scopes', { method: 'POST', body: JSON.stringify({ name, cidr, zone: 'default' }) }); setName(''); setCidr(''); refresh(); } catch (e) { setError(e.message); } } async function approve(id) { try { await api(`/v1/inventory/scopes/${id}/approve`, { method: 'POST' }); refresh(); } catch (e) { setError(e.message); } } return <><Form title="Add inventory scope" onSubmit={add}><input placeholder="Name" value={name} onChange={e => setName(e.target.value)} required/><input placeholder="10.42.0.0/16" value={cidr} onChange={e => setCidr(e.target.value)} required/><button>Add scope</button></Form><Table headers={['Name','CIDR','Zone','Approval','']} rows={scopes.map(s => [s.name,s.cidr,s.zone,<Status value={s.approved ? 'approved' : 'pending'} />,!s.approved && <button onClick={() => approve(s.id)}>Approve</button>])} /></>; }
function Profiles({ profiles, refresh, setError }) { const [name, setName] = useState(''); const [ports, setPorts] = useState('22,80,443'); async function add(e) { e.preventDefault(); try { await api('/v1/scan-profiles', { method: 'POST', body: JSON.stringify({ name, ports, max_rate: 100, max_concurrent_shards: 4, timeout_seconds: 900, zone: 'default' }) }); setName(''); refresh(); } catch (e) { setError(e.message); } } return <><Form title="Create profile" onSubmit={add}><input placeholder="Profile name" value={name} onChange={e => setName(e.target.value)} required/><input value={ports} onChange={e => setPorts(e.target.value)} required/><button>Create</button></Form><Table headers={['Name','Version','Ports','Rate','Concurrent']} rows={profiles.map(p => [p.name,p.version,p.ports,p.max_rate,p.max_concurrent_shards])} /></>; }
function Runs({ runs, scopes, profiles, refresh, setError }) { const [scope, setScope] = useState(''); const [profile, setProfile] = useState(''); const [selected, setSelected] = useState(null); async function start(e) { e.preventDefault(); try { await api('/v1/scan-runs', { method: 'POST', body: JSON.stringify({ inventory_scope_id: scope, profile_id: profile }) }); refresh(); } catch (e) { setError(e.message); } } async function cancel(id) { try { await api(`/v1/scan-runs/${id}/cancel`, { method: 'POST' }); refresh(); } catch (e) { setError(e.message); } } return <><Form title="Start authorized scan" onSubmit={start}><select value={scope} onChange={e => setScope(e.target.value)} required><option value="">Approved scope</option>{scopes.filter(s => s.approved).map(s => <option key={s.id} value={s.id}>{s.name} · {s.cidr}</option>)}</select><select value={profile} onChange={e => setProfile(e.target.value)} required><option value="">Scan profile</option>{profiles.map(p => <option key={p.id} value={p.id}>{p.name} v{p.version}</option>)}</select><button>Start run</button></Form><RunTable runs={runs} onCancel={cancel} onReview={setSelected} />{selected && <Results run={selected} onClose={() => setSelected(null)} setError={setError} />}</>; }
function RunTable({ runs, onCancel, onReview }) { return <Table headers={['Created','Status','Shards','Requested by','']} rows={runs.map(r => [stamp(r.created_at),<Status value={r.status} />,`${r.shards.filter(s => s.status === 'completed').length}/${r.shards.length} completed`,r.requested_by,<span className="actions">{onReview && <button className="secondary" onClick={() => onReview(r)}>Review</button>}{active.has(r.status) && onCancel && <button className="danger" onClick={() => onCancel(r.id)}>Cancel</button>}</span>])} />; }
function Results({ run, onClose, setError }) { const [hosts, setHosts] = useState([]); const [offset, setOffset] = useState(0); const pageSize = 50; useEffect(() => { api(`/v1/scan-runs/${run.id}/hosts?limit=${pageSize}&offset=${offset}`).then(setHosts).catch(e => setError(e.message)); }, [run.id, offset]); const complete = run.shards.filter(s => s.status === 'completed').length; return <section className="results"><header><div><p className="eyebrow">RUN RESULTS</p><h2>{run.id}</h2><p>{complete}/{run.shards.length} shards complete · <Status value={run.status} /></p></div><button className="secondary" onClick={onClose}>Close results</button></header><h3>Discovered hosts</h3><Table headers={['Address','Hostname','State','Services']} rows={hosts.map(host => [host.address,host.hostname,<Status value={host.state} />,host.services.length ? <ul className="services">{host.services.map(service => <li key={`${service.protocol}-${service.port}`}><b>{service.port}/{service.protocol}</b> <Status value={service.state} /> {service.service || 'unknown'} {[service.product, service.version].filter(Boolean).join(' ')}</li>)}</ul> : 'No ports reported'])} /><div className="pager"><button className="secondary" disabled={!offset} onClick={() => setOffset(Math.max(0, offset-pageSize))}>Previous</button><span>Showing {offset + 1}–{offset + hosts.length}</span><button className="secondary" disabled={hosts.length < pageSize} onClick={() => setOffset(offset + pageSize)}>Next</button></div><h3>Shard outcomes</h3><Table headers={['CIDR','Status','Attempts','Artifact','Error']} rows={run.shards.map(shard => [shard.cidr,<Status value={shard.status} />,shard.attempts,shard.artifact_key || '—',shard.error || '—'])} /></section>; }
function Schedules({ schedules, scopes, profiles, refresh, setError }) { const [scope, setScope] = useState(''); const [profile, setProfile] = useState(''); const [name,setName] = useState(''); async function create(e) { e.preventDefault(); try { await api('/v1/schedules', { method:'POST', body:JSON.stringify({ name, inventory_scope_id:scope, profile_id:profile, interval_minutes:1440, timezone:'UTC' }) }); refresh(); } catch(e) { setError(e.message); } } async function disable(id) { try { await api(`/v1/schedules/${id}/disable`, {method:'POST'}); refresh(); } catch(e) { setError(e.message); } } return <><Form title="Create daily schedule" onSubmit={create}><input placeholder="Name" value={name} onChange={e=>setName(e.target.value)} required/><select value={scope} onChange={e=>setScope(e.target.value)} required><option value="">Scope</option>{scopes.filter(s=>s.approved).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={profile} onChange={e=>setProfile(e.target.value)} required><option value="">Profile</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button>Schedule</button></Form><Table headers={['Name','Interval','Next run','Status','']} rows={schedules.map(s=>[s.name,`${s.interval_minutes} min`,stamp(s.next_run_at),<Status value={s.enabled?'enabled':'disabled'} />,s.enabled&&<button onClick={()=>disable(s.id)}>Disable</button>])}/></>; }
function Audit({ audit }) { return <Table headers={['Time','Actor','Action','Resource']} rows={audit.map(a=>[stamp(a.created_at),a.actor,a.action,`${a.resource_type} ${a.resource_id}`])} />; }
function Form({ title, children, onSubmit }) { return <form className="form" onSubmit={onSubmit}><h2>{title}</h2><div>{children}</div></form>; }
function Table({ headers, rows }) { return <div className="table"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell || '—'}</td>)}</tr>) : <tr><td colSpan={headers.length}>No data yet.</td></tr>}</tbody></table></div>; }
createRoot(document.getElementById('root')).render(<App />);
