{{- if and (not .Values.env.existingSecret) .Values.env.databaseUrl .Values.env.amqpUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transport-lookout.credentialsSecretName" . }}
type: Opaque
stringData:
  {{ .Values.env.databaseUrlKey }}: {{ .Values.env.databaseUrl | quote }}
  {{ .Values.env.amqpUrlKey }}: {{ .Values.env.amqpUrl | quote }}
{{- end }}
