apiVersion: v1
kind: Service
metadata:
  name: {{ include "transport-lookout.fullname" . }}
  labels: { app: {{ include "transport-lookout.fullname" . }}-api }
spec:
  selector: { app: {{ include "transport-lookout.fullname" . }}-api }
  ports: [{ name: http, port: {{ .Values.service.port }}, targetPort: 8080 }]
