{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "transport-lookout.fullname" . }}
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    app.kubernetes.io/name: transport-lookout
spec:
  selector:
    matchLabels:
      app: {{ include "transport-lookout.fullname" . }}-api
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.scrapeInterval }}
{{- end }}
