image:
  repository: transport-lookout
  tag: latest
  pullPolicy: IfNotPresent
replicas: 2
workerReplicas: 2
service:
  port: 8080
env:
  databaseUrl: ""
  amqpUrl: ""
  bootstrapEnabled: "false"
nodeSelector: {}
